import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

final themeModeProvider = StateProvider<ThemeMode>((ref) => ThemeMode.system);

class AppTheme {
  static final lightTheme = FlexThemeData.light(
    colors: const FlexSchemeColor(
      primary: Color(0xFF6366F1),
      primaryContainer: Color(0xFFE0E7FF),
      secondary: Color(0xFF8B5CF6),
      secondaryContainer: Color(0xFFF3E8FF),
      tertiary: Color(0xFF06B6D4),
      tertiaryContainer: Color(0xFFECFEFF),
      appBarColor: Color(0xFFE0E7FF),
      error: Color(0xFFEF4444),
    ),
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 7,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 10,
      blendOnColors: false,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      alignedDropdown: true,
      useInputDecoratorThemeInDialogs: true,
      appBarCenterTitle: false,
      appBarScrolledUnderElevation: 0.0,
      bottomSheetModalBackgroundColor: Color(0xFFFAFAFA),
      cardElevation: 0.5,
      cardRadius: 12.0,
      chipRadius: 8.0,
      dialogRadius: 16.0,
      dialogElevation: 3.0,
      drawerRadius: 16.0,
      drawerElevation: 1.0,
      dropdownMenuBorderRadius: 8.0,
      elevatedButtonBorderRadius: 8.0,
      elevatedButtonElevation: 1.0,
      filledButtonBorderRadius: 8.0,
      floatingActionButtonBorderRadius: 16.0,
      inputDecoratorBorderRadius: 8.0,
      inputDecoratorFillColor: Color(0xFFF8FAFC),
      menuRadius: 8.0,
      menuBarRadius: 8.0,
      menuBarElevation: 2.0,
      navigationBarElevation: 0.0,
      navigationBarHeight: 70.0,
      navigationBarIndicatorRadius: 12.0,
      navigationRailElevation: 0.0,
      navigationRailUseIndicator: true,
      navigationRailIndicatorRadius: 12.0,
      outlinedButtonBorderRadius: 8.0,
      popupMenuRadius: 8.0,
      popupMenuElevation: 3.0,
      popupMenuOpacity: 1.0,
      snackBarRadius: 8.0,
      snackBarElevation: 4.0,
      textButtonBorderRadius: 8.0,
      textFieldRadius: 8.0,
      timePickerDialogRadius: 16.0,
      toggleButtonsBorderRadius: 8.0,
      unselectedToggleIsColored: true,
      useFlutterDefaults: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: 'Inter',
  );

  static final darkTheme = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xFF818CF8),
      primaryContainer: Color(0xFF312E81),
      secondary: Color(0xFFA78BFA),
      secondaryContainer: Color(0xFF6B21A8),
      tertiary: Color(0xFF22D3EE),
      tertiaryContainer: Color(0xFF0F172A),
      appBarColor: Color(0xFF312E81),
      error: Color(0xFFF87171),
    ),
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 13,
    darkIsTrueBlack: false,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      alignedDropdown: true,
      useInputDecoratorThemeInDialogs: true,
      appBarCenterTitle: false,
      appBarScrolledUnderElevation: 0.0,
      bottomSheetModalBackgroundColor: Color(0xFF0F172A),
      cardElevation: 0.5,
      cardRadius: 12.0,
      chipRadius: 8.0,
      dialogRadius: 16.0,
      dialogElevation: 3.0,
      drawerRadius: 16.0,
      drawerElevation: 1.0,
      dropdownMenuBorderRadius: 8.0,
      elevatedButtonBorderRadius: 8.0,
      elevatedButtonElevation: 1.0,
      filledButtonBorderRadius: 8.0,
      floatingActionButtonBorderRadius: 16.0,
      inputDecoratorBorderRadius: 8.0,
      inputDecoratorFillColor: Color(0xFF1E293B),
      menuRadius: 8.0,
      menuBarRadius: 8.0,
      menuBarElevation: 2.0,
      navigationBarElevation: 0.0,
      navigationBarHeight: 70.0,
      navigationBarIndicatorRadius: 12.0,
      navigationRailElevation: 0.0,
      navigationRailUseIndicator: true,
      navigationRailIndicatorRadius: 12.0,
      outlinedButtonBorderRadius: 8.0,
      popupMenuRadius: 8.0,
      popupMenuElevation: 3.0,
      popupMenuOpacity: 1.0,
      snackBarRadius: 8.0,
      snackBarElevation: 4.0,
      textButtonBorderRadius: 8.0,
      textFieldRadius: 8.0,
      timePickerDialogRadius: 16.0,
      toggleButtonsBorderRadius: 8.0,
      unselectedToggleIsColored: true,
      useFlutterDefaults: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: 'Inter',
  );

  static final amoledTheme = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xFF818CF8),
      primaryContainer: Color(0xFF312E81),
      secondary: Color(0xFFA78BFA),
      secondaryContainer: Color(0xFF6B21A8),
      tertiary: Color(0xFF22D3EE),
      tertiaryContainer: Color(0xFF0F172A),
      appBarColor: Color(0xFF312E81),
      error: Color(0xFFF87171),
    ),
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 13,
    darkIsTrueBlack: true,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      alignedDropdown: true,
      useInputDecoratorThemeInDialogs: true,
      appBarCenterTitle: false,
      appBarScrolledUnderElevation: 0.0,
      bottomSheetModalBackgroundColor: Colors.black,
      cardElevation: 0.5,
      cardRadius: 12.0,
      chipRadius: 8.0,
      dialogRadius: 16.0,
      dialogElevation: 3.0,
      drawerRadius: 16.0,
      drawerElevation: 1.0,
      dropdownMenuBorderRadius: 8.0,
      elevatedButtonBorderRadius: 8.0,
      elevatedButtonElevation: 1.0,
      filledButtonBorderRadius: 8.0,
      floatingActionButtonBorderRadius: 16.0,
      inputDecoratorBorderRadius: 8.0,
      inputDecoratorFillColor: Color(0xFF1C1C1E),
      menuRadius: 8.0,
      menuBarRadius: 8.0,
      menuBarElevation: 2.0,
      navigationBarElevation: 0.0,
      navigationBarHeight: 70.0,
      navigationBarIndicatorRadius: 12.0,
      navigationRailElevation: 0.0,
      navigationRailUseIndicator: true,
      navigationRailIndicatorRadius: 12.0,
      outlinedButtonBorderRadius: 8.0,
      popupMenuRadius: 8.0,
      popupMenuElevation: 3.0,
      popupMenuOpacity: 1.0,
      snackBarRadius: 8.0,
      snackBarElevation: 4.0,
      textButtonBorderRadius: 8.0,
      textFieldRadius: 8.0,
      timePickerDialogRadius: 16.0,
      toggleButtonsBorderRadius: 8.0,
      unselectedToggleIsColored: true,
      useFlutterDefaults: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: 'Inter',
  );
}

class AppColors {
  static const primary = Color(0xFF6366F1);
  static const secondary = Color(0xFF8B5CF6);
  static const accent = Color(0xFF06B6D4);
  static const success = Color(0xFF10B981);
  static const warning = Color(0xFFF59E0B);
  static const error = Color(0xFFEF4444);
  
  static const glassWhite = Color(0x20FFFFFF);
  static const glassBlack = Color(0x20000000);
  
  static const gradientPrimary = LinearGradient(
    colors: [Color(0xFF6366F1), Color(0xFF8B5CF6)],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );
  
  static const gradientSecondary = LinearGradient(
    colors: [Color(0xFF06B6D4), Color(0xFF22D3EE)],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );
}